-- Replayed into every demo schema during a sandbox reset, so nothing here may
-- name a schema. A single "public.users" would write to the wrong one.

CREATE TABLE users (
  id          INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT        NOT NULL,
  email       TEXT        NOT NULL UNIQUE,
  age         INTEGER,
  department  TEXT,
  salary      INTEGER,
  hired_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  manager_id  INTEGER     REFERENCES users (id) ON DELETE SET NULL
);

-- Postgres indexes primary keys and unique columns automatically, never
-- foreign keys. The recursive org chart walk needs this one.
CREATE INDEX users_manager_id_idx ON users (manager_id);

CREATE TABLE posts (
  id          INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT        NOT NULL,
  content     TEXT        NOT NULL,
  published   BOOLEAN     NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  author_id   INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE products (
  id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT          NOT NULL,
  -- Money, so NUMERIC. A float can't hold 19.90 exactly.
  price       NUMERIC(10,2) NOT NULL,
  stock       INTEGER       NOT NULL DEFAULT 0,
  category    TEXT          NOT NULL,
  -- Default to an empty array so the array operators never meet a NULL.
  tags        TEXT[]        NOT NULL DEFAULT '{}',
  metadata    JSONB,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE orders (
  id          INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status      TEXT        NOT NULL DEFAULT 'pending',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id     INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE order_items (
  id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantity    INTEGER       NOT NULL,
  -- Snapshot of the price when the order was placed, not the current one.
  unit_price  NUMERIC(10,2) NOT NULL,
  order_id    INTEGER       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  product_id  INTEGER       NOT NULL REFERENCES products (id) ON DELETE CASCADE
);

-- Foreign keys aren't indexed automatically, and all four of these get joined on.
CREATE INDEX posts_author_id_idx        ON posts (author_id);
CREATE INDEX orders_user_id_idx         ON orders (user_id);
CREATE INDEX order_items_order_id_idx   ON order_items (order_id);
CREATE INDEX order_items_product_id_idx ON order_items (product_id);
