-- Lives only in public and is never replayed into a demo schema, 
-- so every name here is written out in full.

-- gen_random_bytes lives in pgcrypto.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.sandboxes (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schema_name   TEXT          NOT NULL UNIQUE,
  token         TEXT          UNIQUE,
  claimed_at    TIMESTAMPTZ,
  last_seen_at  TIMESTAMPTZ
);

-- Claiming picks the least recently used row, so it reads this index.
CREATE INDEX IF NOT EXISTS sandboxes_last_seen_at_idx
  ON public.sandboxes (last_seen_at NULLS FIRST)